repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.9

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.17.0
  #   hooks:
  #     - id: pylint
  #       name: pylint (score >= 9 required)
  #       args:
  #         - --fail-under=9
  #         - --ignore=.pytest_cache,__pycache__,.venv,fraud_detection_env,
  #         - -v #verbose
  #       language_version: python3.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  # Local repository for custom hooks.
  # This hook runs pytest with coverage enforcement to ensure code quality
  # and maintain a minimum test coverage threshold of 80%.
  - repo: local
    hooks:
      - id: pytest-coverage
        name: Run pytest with coverage and enforce minimum coverage
        entry: >
          pytest
          --cov=.
          --cov-report=term
          --cov-fail-under=80
          --maxfail=1
          --disable-warnings
          -q
          --ignore=.venv
          --ignore=env
          --ignore=venv
          --ignore=__pycache__
          --ignore=build
          --ignore=dist
        language: system
        pass_filenames: false
        args: []