repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: ["--exit-zero"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: pytest --cov=./ --cov-fail-under=80
        language: system
        types: [python]
