repos:
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.15.0
    hooks:
      - id: pylint
        args: ["--exit-zero"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: pytest --cov=./ --cov-fail-under=80
        language: system
        types: [python]
