name: fraud_detection_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
    - numpy==2.0.2
    - pandas==2.2.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - six==1.17.0
    - tzdata==2025.2
    - pylint>=2.15
    - pytest>=7.0
    - pytest-cov>=4.0
    - pre-commit>=3.0
