name: Conda Environment Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: fraud_detection_env
          python-version: 3.9  # match your .yml version
          auto-update-conda: true

      - name: Install pytest and coverage tools
        shell: bash -l {0}
        run: |
          conda activate fraud_detection_env
          pip install pytest pytest-cov

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          conda activate fraud_detection_env
          pytest --cov=src --cov-report=term --cov-fail-under=80
